// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5HJnh8lSKVG-C0uI4_nmdTz9yAxhH4NQ',
    appId: '1:380802237826:web:011ff5ab65903f962abb9b',
    messagingSenderId: '380802237826',
    projectId: 'bomberman-f2f4c',
    authDomain: 'bomberman-f2f4c.firebaseapp.com',
    databaseURL: 'https://bomberman-f2f4c-default-rtdb.firebaseio.com',
    storageBucket: 'bomberman-f2f4c.firebasestorage.app',
    measurementId: 'G-4RJH112G9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOKj0oak7PEtpDRE2JqboKD5gzukuLm1I',
    appId: '1:380802237826:android:4ff54e33bc7783762abb9b',
    messagingSenderId: '380802237826',
    projectId: 'bomberman-f2f4c',
    databaseURL: 'https://bomberman-f2f4c-default-rtdb.firebaseio.com',
    storageBucket: 'bomberman-f2f4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtxXX_ypVkoWDIVN_A7my6t7UbJ-ejkms',
    appId: '1:380802237826:ios:b1306841b16cb97e2abb9b',
    messagingSenderId: '380802237826',
    projectId: 'bomberman-f2f4c',
    databaseURL: 'https://bomberman-f2f4c-default-rtdb.firebaseio.com',
    storageBucket: 'bomberman-f2f4c.firebasestorage.app',
    iosBundleId: 'com.example.blastermanGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtxXX_ypVkoWDIVN_A7my6t7UbJ-ejkms',
    appId: '1:380802237826:ios:b1306841b16cb97e2abb9b',
    messagingSenderId: '380802237826',
    projectId: 'bomberman-f2f4c',
    databaseURL: 'https://bomberman-f2f4c-default-rtdb.firebaseio.com',
    storageBucket: 'bomberman-f2f4c.firebasestorage.app',
    iosBundleId: 'com.example.blastermanGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5HJnh8lSKVG-C0uI4_nmdTz9yAxhH4NQ',
    appId: '1:380802237826:web:e702d02b048100fd2abb9b',
    messagingSenderId: '380802237826',
    projectId: 'bomberman-f2f4c',
    authDomain: 'bomberman-f2f4c.firebaseapp.com',
    databaseURL: 'https://bomberman-f2f4c-default-rtdb.firebaseio.com',
    storageBucket: 'bomberman-f2f4c.firebasestorage.app',
    measurementId: 'G-DZ3WF9YJPV',
  );
}
