// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-FGTetnSwIlV0wORLUHN-MV9pLjDdpPs',
    appId: '1:429222388918:web:0673a013221af4283d3217',
    messagingSenderId: '429222388918',
    projectId: 'blaster-man-91d59',
    authDomain: 'blaster-man-91d59.firebaseapp.com',
    databaseURL: 'https://blaster-man-91d59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blaster-man-91d59.firebasestorage.app',
    measurementId: 'G-S79FE0H1MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpdHSGFvO6ICfQzyYsYP0YUdX3yA2FBA',
    appId: '1:429222388918:android:e524677a97f8f5d13d3217',
    messagingSenderId: '429222388918',
    projectId: 'blaster-man-91d59',
    databaseURL: 'https://blaster-man-91d59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blaster-man-91d59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxV_Fwc6rOMHAi2frlF5TiYQKr7FmmSvQ',
    appId: '1:429222388918:ios:88cad27b00f50c773d3217',
    messagingSenderId: '429222388918',
    projectId: 'blaster-man-91d59',
    databaseURL: 'https://blaster-man-91d59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blaster-man-91d59.firebasestorage.app',
    iosClientId: '429222388918-8mlat8eesp1hf04a9cltamiae126hd2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.blasterman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxV_Fwc6rOMHAi2frlF5TiYQKr7FmmSvQ',
    appId: '1:429222388918:ios:88cad27b00f50c773d3217',
    messagingSenderId: '429222388918',
    projectId: 'blaster-man-91d59',
    databaseURL: 'https://blaster-man-91d59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blaster-man-91d59.firebasestorage.app',
    iosClientId: '429222388918-8mlat8eesp1hf04a9cltamiae126hd2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.blasterman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-FGTetnSwIlV0wORLUHN-MV9pLjDdpPs',
    appId: '1:429222388918:web:7fc4470e28f83b573d3217',
    messagingSenderId: '429222388918',
    projectId: 'blaster-man-91d59',
    authDomain: 'blaster-man-91d59.firebaseapp.com',
    databaseURL: 'https://blaster-man-91d59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'blaster-man-91d59.firebasestorage.app',
    measurementId: 'G-NCYRJ06QC8',
  );

}